"""added email to user

Revision ID: 05eeabb86281
Revises: 9b02d820f29b
Create Date: 2021-02-09 13:45:02.649830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05eeabb86281'
down_revision = '9b02d820f29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
